export const ADD_FLATE_REQUEST = "ADD_FLATE_REQUEST";
export const ADD_FLATE_SUCCESS = "ADD_FLATE_SUCCESS";
export const ADD_FLATE_FAILURE = "ADD_FLATE_FAILURE";

export const EDIT_FLATE_REQUEST = "EDIT_FLATE_REQUEST";
export const EDIT_FLATE_SUCCESS = "EDIT_FLATE_SUCCESS";
export const EDIT_FLATE_FAILURE = "EDIT_FLATE_FAILURE";

export const DELETE_FLATE_REQUEST = "DELETE_FLATE_REQUEST";
export const DELETE_FLATE_SUCCESS = "DELETE_FLATE_SUCCESS";
export const DELETE_FLATE_FAILURE = "DELETE_FLATE_FAILURE";

export const HANDLE_STATE = "HANDLE_STATE"